apiVersion: v1
kind: Service
metadata:
  name: {{ include "d3hard.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "d3hard.name" . }}
    helm.sh/chart: {{ include "d3hard.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
    
  selector:
    app.kubernetes.io/name: {{ include "d3hard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
