# Default values for d3hard.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: YOUR_DOCKER_REGISTRY/d3hard
  tag: v8
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

appLogLevel: INFO

db:
  jdbc: jdbc:mysql://mysql-service:3306/d3hard
  username: d3hard
  password: d3hardPassword

blizzard:
  clientId: YOUR_CLIENT_ID
  secret: YOUR_CLIENT_SECRET

season:
  minValue: 12
  maxValue: 16