apiVersion: v1
kind: Pod
metadata:
  name: import-api-konta-once
spec:       
  containers:      
  - name: d3hard
    image: "YOUR_DOCKER_REGISTRY/d3hard:v8"
    command: ["java"]
    args: ["-jar", "app.jar", "forum", "--jdbc=jdbc:mysql://d3env-mysql-service:3306/d3db?useSSL=false&user=d3user&password=gUNup0CdkTio", "--url=http://d3env-d3hard:9000"]          
  restartPolicy: Never




